
import React from 'react';
import { Button } from './Button';

interface DisclaimerModalProps {
  onAccept: () => void;
}

export const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ onAccept }) => {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
      <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-2xl max-w-md w-full p-8 border border-gray-200 dark:border-slate-700">
        <div className="text-center mb-6">
          <div className="w-16 h-16 bg-yellow-100 dark:bg-yellow-900/30 rounded-full flex items-center justify-center mx-auto mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 text-yellow-600 dark:text-yellow-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
          </div>
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Important Disclaimer</h2>
        </div>
        
        <div className="space-y-4 text-gray-600 dark:text-slate-300 text-sm mb-8 leading-relaxed">
          <p>
            The <strong>CA AI Agent</strong> is an artificial intelligence tool designed for educational and informational purposes only.
          </p>
          <p className="bg-yellow-50 dark:bg-yellow-900/20 p-3 rounded-lg border border-yellow-100 dark:border-yellow-900/30 text-yellow-800 dark:text-yellow-200">
            <strong>This tool does not provide professional financial, legal, or tax advice.</strong>
          </p>
          <p>
            Any outputs generated by this AI should be verified by a qualified Chartered Accountant or financial professional before being used for official filings or decision-making. We accept no liability for errors or omissions.
          </p>
        </div>

        <Button onClick={onAccept}>
          I Understand & Agree
        </Button>
      </div>
    </div>
  );
};
